esphome:
  name: livingroom-rgbww
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

light:
  - platform: rgbww
    name: livingroom_rgbww
    id: livingroom_rgbww
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    cold_white: pwm_cw
    warm_white: pwm_ww
    cold_white_color_temperature: 5750 K
    warm_white_color_temperature: 3050 K
    effects:
      - lambda:
          name: rainbow
          update_interval: 60s
          lambda: |-
            static int transition_length = 55;
            static double colors[][3] {
              {1.0, 0.0, 0.0},
              {1.0, 1.0, 0.0},
              {0.0, 1.0, 0.0},
              {0.0, 1.0, 1.0},
              {0.0, 0.0, 1.0},
              {1.0, 0.0, 1.0},
            };

            // code
            static int state = 0;
            static int total_states = sizeof(colors) / sizeof(colors[0]);

            auto call = id(livingroom_rgbww).turn_on();

            ESP_LOGD("livingroom_rgbww", "state: %i/%i", state+1, total_states);

            call.set_transition_length(transition_length * 1000);
            call.set_rgb(colors[state][0], colors[state][1], colors[state][2]);
            call.perform();

            state = (state + 1) % total_states;

output:
  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 100 Hz
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 100 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 100 Hz
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO04
    frequency: 100 Hz
    id: pwm_cw

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 100 Hz
    id: pwm_ww
  